### ISSUE TITLE
What kind of filament is best for this?

### ISSUE THREAD

**Issue by ntatko** [ka-moamoa/Practical_SMFC_Design_Guide#3]
If it's true, that this kind of battery can operate near indefinitely, I'm guessing that PLA is not the right choice, probably PET-G?

**Comment by yebo29** [comment]
The [video](https://dl.acm.org/action/downloadSupplement?doi=10.1145%2F3631410&file=yen.zip) mentions ABS for the scaffold and PLA for the anode clips. Not sure if that's all the pieces; I'm learning about this project just now myself.

**Comment by billyen33** [comment]
ABS or PLA will both work (we've tried both in our setups), and I recommend looking at Appendix A2 in the paper to find the full 3D printing instructions for our cells. We went with PLA for the final prototype because it is more accessible (no fumes) and environmentally friendly (plant-based/compostable). Let us know if you find an alternative material that works better!
